In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [7]:
a=np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3]
(3,)
int32
1
3
4


In [10]:
a=np.array([1,2,3,4])
a[0]=10
print(a)

b=a*np.array([2,0,2,2])
print(b)

[10  2  3  4]
[20  0  6  8]
