In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
a=np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3]
(3,)
int32
1
3
4


In [10]:
a=np.array([1,2,3,4])
a[0]=10
print(a)

b=a*np.array([2,0,2,2])
print(b)

[10  2  3  4]
[20  0  6  8]


In [8]:
#2D array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#vectorize array
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

#addition operation
print(array1+array2)
#subtraction
print(array1 - array2)
#mutliplication
print(array1 * array2)
#division
print(array1 / array2)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [18]:
#array slicing and indexing
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array: \n",array)

array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
